"""empty message

Revision ID: b906edae1b0b
Revises: 267b59260c3c
Create Date: 2023-04-18 16:55:22.045474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b906edae1b0b'
down_revision = '267b59260c3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('barang', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.alter_column('kode_barang',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
        batch_op.drop_index('ix_barang_harga_jual')
        batch_op.drop_index('ix_barang_harga_modal')
        batch_op.create_unique_constraint(None, ['kode_barang'])

    with op.batch_alter_table('terjual', schema=None) as batch_op:
        batch_op.alter_column('kode_barang',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=15),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('terjual', schema=None) as batch_op:
        batch_op.alter_column('kode_barang',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    with op.batch_alter_table('barang', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('ix_barang_harga_modal', ['harga_modal'], unique=False)
        batch_op.create_index('ix_barang_harga_jual', ['harga_jual'], unique=False)
        batch_op.alter_column('kode_barang',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
        batch_op.drop_column('id')

    # ### end Alembic commands ###
