"""barang table

Revision ID: c8fbeeb9656e
Revises: b2d0fbfb010c
Create Date: 2023-04-17 23:04:55.728170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8fbeeb9656e'
down_revision = 'b2d0fbfb010c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('barang',
    sa.Column('kode_barang', sa.String(length=15), nullable=False),
    sa.Column('nama_barang', sa.String(length=30), nullable=True),
    sa.Column('harga_jual', sa.Integer(), nullable=True),
    sa.Column('harga_modal', sa.Integer(), nullable=True),
    sa.Column('tersedia', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('kode_barang')
    )
    with op.batch_alter_table('barang', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_barang_harga_jual'), ['harga_jual'], unique=False)
        batch_op.create_index(batch_op.f('ix_barang_harga_modal'), ['harga_modal'], unique=False)

    with op.batch_alter_table('terjual', schema=None) as batch_op:
        batch_op.add_column(sa.Column('barang_kode_barang', sa.String(length=50), nullable=True))
        batch_op.create_foreign_key(None, 'barang', ['barang_kode_barang'], ['kode_barang'])
        batch_op.drop_column('jual')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('terjual', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jual', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('barang_kode_barang')

    with op.batch_alter_table('barang', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_barang_harga_modal'))
        batch_op.drop_index(batch_op.f('ix_barang_harga_jual'))

    op.drop_table('barang')
    # ### end Alembic commands ###
